### PR TITLE
side panel file browser fix

### LINKED ISSUE #1350: file browser in side panel broken
1) cursor should change to the hand.

2) When click on a directory and then click .., then it displays (no files).

### PR DESCRIPTION
**Pull request by pbhatnagar3**
#1350 fixes the side panel file browser

#### Testing

Please check out this video for testing. It shows the working side panel.
https://www.dropbox.com/s/ogx9u5rkuy3yzvp/side-panel%20fixed.mp4?dl=0

NOTE: Dropbox might be downscaling the video. I have sent the same video on slack (in worksheets channel) if you want to see the HD version.

@percyliang @kashizui please review

### CODE REVIEW

File: codalab/apps/web/static/js/worksheet/worksheet_side_panel.js [hunk 1]
```diff
@@ -234,11 +234,17 @@ var BundleDetailSidePanel = React.createClass({
     },
 
     updateFileBrowser: function(folder_path) {
-        if (folder_path == '..')  // Go to parent directory
-          folder_path = this.state.currentWorkingDirectory.replace(/\/[^\/]*$/, '');
-
-        if (this.state.currentWorkingDirectory != '')
-            folder_path = this.state.currentWorkingDirectory + "/" + folder_path;
+        if (folder_path == '..'){  // Go to parent directory
```
Comment (kashizui) [inline codalab/apps/web/static/js/worksheet/worksheet_side_panel.js]: nit: space before `{` brace

File: codalab/apps/web/static/js/worksheet/worksheet_side_panel.js [hunk 2]
```diff
@@ -576,7 +582,7 @@ var FileBrowserItem = React.createClass({
                 <td>
                     <div className={this.props.type} onClick={this.props.type != 'file' ? this.browseToFolder : null}>
                         <span className={icon} alt="More"></span>
-                        <a href={this.props.type == 'file' ? file_link : null} target="_blank">{this.props.index}</a>
+                        <a href={this.props.type == 'file' ? file_link : null} target="_blank" className='sidepanel-file-viewer-contents'>{this.props.index}</a>
```
Comment (kashizui) [inline codalab/apps/web/static/js/worksheet/worksheet_side_panel.js]: I believe `className` attribute should be `class`? Unless this is React specific

File: codalab/apps/web/static/js/worksheet/worksheet_side_panel.js [hunk 3]
```diff
@@ -234,11 +234,17 @@ var BundleDetailSidePanel = React.createClass({
...
+            folder_path = this.state.currentWorkingDirectory.substring(0, this.state.currentWorkingDirectory.lastIndexOf('/'));
+        }
+        else if (this.state.currentWorkingDirectory != '') {
+            if (folder_path != ''){
+                folder_path = this.state.currentWorkingDirectory + "/" + folder_path;
+            }
+            else {
+                folder_path = this.state.currentWorkingDirectory;
+            }
+        }
```
Comment (kashizui) [inline codalab/apps/web/static/js/worksheet/worksheet_side_panel.js]: what happens if none of these conditions are satisfied? (i.e. `folder_path !== '..'` and `this.state.currentWorkingDirectory === ''`)?

Comment (pbhatnagar3) [inline codalab/apps/web/static/js/worksheet/worksheet_side_panel.js]: This exactly happens on the root of the worksheet. The files and folders present at that folder are returned in that case.

File: codalab/apps/web/static/js/worksheet/worksheet_side_panel.js (hunk 2 above)
Comment (pbhatnagar3) [inline codalab/apps/web/static/js/worksheet/worksheet_side_panel.js]: This is React specific. React requires xml syntax and also we have to use 'className' instead of 'class'. 'class' is a reserved word

File: codalab/apps/web/static/js/worksheet/worksheet_side_panel.js (hunk 1 above)
Comment (pbhatnagar3) [inline codalab/apps/web/static/js/worksheet/worksheet_side_panel.js]: Thanks. I will make that change.

**Comment by kashizui** [comment]
LGTM
